version: '3.2'

services:
   zoo1:
      container_name: zoo1
      image: zookeeper
      hostname: zoo1
      ports:
         - 12181:2181
      environment:
         ALLOW_ANONYMOUS_LOGIN: yes
         ZOO_MY_ID: 1
         ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      volumes:
         - ./zookeeper/zoo1/data:/data
         - ./zookeeper/zoo1/datalog:/datalog

   zoo2:
      container_name: zoo2
      image: zookeeper
      hostname: zoo2
      ports:
         - 22181:2181
      environment:
         ALLOW_ANONYMOUS_LOGIN: yes
         ZOO_MY_ID: 2
         ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      volumes:
         - ./zookeeper/zoo2/data:/data
         - ./zookeeper/zoo2/datalog:/datalog

   zoo3:
      container_name: zoo3
      image: zookeeper
      hostname: zoo3
      ports:
         - 32181:2181
      environment:
         ALLOW_ANONYMOUS_LOGIN: yes
         ZOO_MY_ID: 3
         ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      volumes:
         - ./zookeeper/zoo3/data:/data
         - ./zookeeper/zoo3/datalog:/datalog

   kafka1:
      container_name: kafka1
      image: docker.io/bitnami/kafka:latest
      hostname: kafka1
      ports:
         - 19092:9092
         - 19093:9093
      environment:
         - KAFKA_BROKER_ID=1
         - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
         - ALLOW_PLAINTEXT_LISTENER=yes
         - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
         - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
         - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://192.168.0.101:19093
         - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      volumes:
         - ./kafka/kafka1:/bitnami/kafka
      depends_on:
         - zoo1
         - zoo2
         - zoo3

   kafka2:
      container_name: kafka2
      image: docker.io/bitnami/kafka:latest
      hostname: kafka2
      ports:
         - 29092:9092
         - 29093:9093
      environment:
         - KAFKA_BROKER_ID=2
         - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
         - ALLOW_PLAINTEXT_LISTENER=yes
         - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
         - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
         - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://192.168.0.101:29093
         - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      volumes:
         - ./kafka/kafka2:/bitnami/kafka
      depends_on:
         - zoo1
         - zoo2
         - zoo3

   kafka3:
      container_name: kafka3
      image: docker.io/bitnami/kafka:latest
      hostname: kafka3
      ports:
         - 39092:9092
         - 39093:9093
      environment:
         - KAFKA_BROKER_ID=3
         - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
         - ALLOW_PLAINTEXT_LISTENER=yes
         - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
         - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
         - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9092,EXTERNAL://192.168.0.101:39093
         - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      volumes:
         - ./kafka/kafka3:/bitnami/kafka
      depends_on:
         - zoo1
         - zoo2
         - zoo3
