version: '3.2'
services:
   mssql:
      container_name: mssql
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports:
         - '1433:1433'
      env_file:
         - ../env/dev.env
   #      volumes:
   #         - ./mssql.db/data:/var/opt/mssql/data
   #         - ./mssql.db/log:/var/opt/mssql/log
   #         - ./mssql.db/secrets:/var/opt/mssql/secrets

   admin:
      container_name: adminer
      image: adminer
      restart: always
      depends_on:
         - mssql
      ports:
         - 8070:8080
