version: '3.2'
services:
   mssql:
      container_name: mssql
      image: mcr.microsoft.com/mssql/server:2019-latest
      user: root # so we can use volumes
      ports:
         - '1433:1433'
      env_file:
         - ../env/dev.env
      volumes:
         - ./mssql.db:/var/opt/mssql
   #         - ./mssql.db/log:/var/opt/mssql/loog
   #         - ./mssql.db/secrets:/var/opt/mssql/secrets

   admin:
      container_name: adminer
      image: adminer
      restart: always
      depends_on:
         - mssql
      ports:
         - 8070:8080

   splunk:
      hostname: splunk
      image: splunk/splunk:latest
      environment:
         SPLUNK_START_ARGS: --accept-license
         SPLUNK_ENABLE_LISTEN: 9997
         SPLUNK_ADD: tcp 1514
         SPLUNK_PASSWORD: splunkpw
      volumes:
         - opt-splunk-etc:/opt/splunk/etc
         - opt-splunk-var:/opt/splunk/var
      ports:
         - '8060:8000'
         - '9997:9997'
         - '8068:8088'
         - '1514:1514'

volumes:
   opt-splunk-etc:
   opt-splunk-var:
