version: '3.1'
services:
   db:
      container_name: db
      image: postgres:14-alpine
      ports:
         - '5432:5432'
      env_file:
         - ../env/dev.env

   admin:
      container_name: adminer
      image: adminer
      restart: always
      depends_on:
         - db
      ports:
         - 8070:8080
